### ISSUE TITLE
override cursorColor

### ISSUE THREAD

**Issue by norbertpy** [mmcbride1007/hyperterm-electron-theme#6]
Thanks for this beautiful theme. I noticed that setting `cursorColor` in my `.hyper.js` file doesn't change its color. Is there any way I can override your default color?

**Comment by mikemcbride** [comment]
hey! thanks for the feedback. I'd encourage you to head over to [hyper-electron-highlighter](https://github.com/mmcbride1007/hyper-electron-highlighter), as this one is deprecated.

It looks like that would still be an issue over there too, but I'll definitely add in a config option to prefer your local setting for cursorColor. Thanks!

**Comment by mikemcbride** [comment]
This is so reasonable I'm gonna add it in... Appreciate the feedback 😄

**Comment by norbertpy** [comment]
Thanks man.
